community:
  enabled: true

image:
  repository: sonarqube
  tag: 25.12.0.117093-community
  pullPolicy: IfNotPresent

postgresql:
  enabled: true
  auth:
    username: sonar
    password: sonar
    database: sonarqube

persistence:
  enabled: false

monitoringPasscodeSecretName: sonarqube-monitoring
monitoringPasscodeSecretKey: monitoringPasscode

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
